### ISSUE TITLE
Cannot specify project paths in `kerblam.toml`

### ISSUE THREAD

**Issue by MrHedmad** [MrHedmad/kerblam#11]
All project paths (e.g. `./data`, `./data/in`, `./src/dockerfiles/`, etc...) are hardcoded.
It would be nice to have a `kerblam.toml` section that can be used to configure these paths for the user, for example:
```toml
[paths]
data = "./data"
input_data = "./data/in"
# ...
```
And then Kerblam! would follow those paths instead of the original, hardcoded ones.
