### ISSUE TITLE
Allow multiple profiles simultaneously

### ISSUE THREAD

**Issue by MrHedmad** [MrHedmad/kerblam#31]
It might be useful to trigger multiple profiles at once.

Consider a pipeline `execute` such that `A + B -> C`, where `A` is a data file and `B` is a configuration file.
One might want to switch the input data `A` to something else (`A'`) with the same config `B`, swap just the config, or swap both.

Kerblam! allows just one profile at a time. This feature can be manually implemented by specifying both swaps in a new profile:
```toml
[data.profiles.config2]
B = B'

[data.profiles.data2]
A = A'

[data.profiles.config2data2]
B = B'
A = A'
```
But it would be better to allow `kerblam run --profile config2 --profile data2 execute` (or even better `kerblam run --profile config2 data2 execute`, and drop the `config2data2` profile altogether.

The issue arises of what profile should take precedence when swapping the same file:
```toml
[data.profiles.generic]
A = A'
B = B'

[data.profiles.conflict]
B = B''
C = C'
```
What should `kerblam run --profile generic,conflict` do? The `B` file conflicts; should it be ultimately swapped with `B'` or `B''`?
I guess one could follow the profile order, having the first profile be the 'main' profile, and so on (e.g. in the above example swap with `B'`), but it would be very fragile.
Another possibility is to disallow conflicts altogether. In that case, the two profiles would be mutually exclusive. This latter approach is less flexible but more robust and explicit, so I think it should be preferred.
