### ISSUE TITLE
Non-fetcheable remote files

### ISSUE THREAD

**Issue by MrHedmad** [MrHedmad/kerblam#75]
There might be some cases where a pipeline fetches data in a non-trivial way, and therefore Kerblam! cannot handle it with a get request. In these cases it might be useful to specify extra remote files so that we can cleanup and pack correctly.

E.g. In the kerblam.toml:
```toml
[data.remote]
"extra" = ["file_1", "file_two"]
```

Allowing regex patterns in such cases (maybe with a specific syntax, like `/some_regex/`) might also be useful.
