### ISSUE TITLE
Mask files in profiles

### ISSUE THREAD

**Issue by MrHedmad** [MrHedmad/kerblam#76]
Sometimes it can be useful to outright hide files during a profile, so that  the pipelines cannot pick them up.

Having an option whereas writing:
```toml
[data.profiles.alternate]
"input.txt" = "_" # Or some other "null" 
```

Would hide the file for some time. This could be done by renaming to something like `filename.hidden` or moving it to a temporary directory near `/data/in`.
