### ISSUE TITLE
Allow `kerblam run` to have a default `test` profile

### ISSUE THREAD

**Issue by MrHedmad** [MrHedmad/kerblam#8]
During testing, it's often the case that real data must be swapped with test data (e.g. `input.txt` swaps with `test_input.txt`, etc...).

It would be useful if Kerblam! had a default profile for this case, assuming that all files `<slug>` must be swapped with `test_<slug>` when running `kerblam run --profile test`, as if you had written the following TOML:
```toml
[data.profiles.test]
"input.csv" = "test_input.csv"
"other.txt" = "test_other.txt"
```
In this way one could simply place test files alongside normal files and execute test runs with ease, without any configuration.

If the user writes their own `data.profiles.test` profile, this behavior must be overridden.
