### ISSUE TITLE
`kerblam run` does not check if a profile would destroy files

### ISSUE THREAD

**Issue by MrHedmad** [MrHedmad/kerblam#9]
Assume this `kerblam.toml`:
```toml
[data.profiles.alternate]
"input.csv" = "other.csv"
```
This causes kerblam! to rename `input.csv` to `input.csv.original` in-place if the profile is executed, without checking if an `input.csv.original` file already exists.

This chance is remote, but to be on the safe side, kerblam! should fail before applying the profile if any of its renames would overwrite already-existing files.
